apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-clone-app
  template:
    metadata:
      labels:
        app: nodejs-clone-app
    spec:
      containers:
        - name: reddit-clone-app
          image: aasaithambi5/node-js-pipeline:1.0.0-3
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
